site:
  title: Wildlife Watcher
  start_page: wildlife-watcher::index.adoc
content:
  sources:
    # - url: https://github.com/wild-horses/wildlife-watcher-kata
    #   branches: [add-antora]
    #   start_path: docs
    - url: .
      branches: [HEAD]
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
